### PR TITLE
190 upgrade geoserver connection

### PR DESCRIPTION
**Pull request by ywkim312**
This PR has been deployed to dev. So when you test it, using the dev and create a dataset using shapefile or zip file of shapefile or geotiff. After you create dataset and attach the geographic data to the dataset, please see the preview. If you see the preview without any problem, this PR is working okay. 

Please DO NOT FORGET to delete the dataset you posted after finishing your test

### CODE REVIEW

**Review by longshuicy — APPROVED** [review]
Tested with posting shapefile to incore-dev. Approve!

**Comment by ylyangtw** [comment]
I am trying to test this. I wonder is this shapefile? Just wanted to make sure I am testing it correctly

```
curl --location 'https://incore-dev.ncsa.illinois.edu/hazard/api/earthquakes' \
--header 'x-auth-userinfo: {"preferred_username":"ylyang"}' \
--header 'x-auth-usergroup: {"groups": ["incore_jupyter"]}' \
--form 'earthquake="{
   \"name\":\"yytest\",
   \"description\":\"yytest\",
   \"eqType\":\"model\",
   \"attenuations\":{
      \"ChiouYoungs2014\":\"1.0\"
   },
   \"eqParameters\":{
      \"srcLatitude\":40.177,
      \"srcLongitude\":-111.426,
      \"magnitude\":\"5.5\",
      \"depth\":\"11.2\",
      \"region\":\"\",
      \"faultTypeMap\":{
         \"ChiouYoungs2014\":\"Normal\"
      }
   },
   \"visualizationParameters\":{
      \"demandType\":\"PGA\",
      \"demandUnits\":\"g\",
      \"minX\":-112.312,
      \"minY\":40.277,
      \"maxX\":-111.462,
      \"maxY\":41,
     
      \"numPoints\":\"1025\",
      \"amplifyHazard\":\"true\"
   }
}"'
```

**Comment by ywkim312** [comment]
@ylyangtw 
[guid_yes.zip](https://github.com/IN-CORE/incore-services/files/12468328/guid_yes.zip)

**Comment by ywkim312** [comment]
@ylyangtw this is a geotiff

**Review by ylyangtw — APPROVED** [review]
posting shapefile and geotiff works well. approve~

**Pull request merged**
