### PR TITLE
fix search mapping

### PR DESCRIPTION
**Pull request by longshuicy**
Test:
GET `http://localhost:8080/dfr3/api/mappings/search?limit=10&skip=0&text=hazus&mappingType=fragility`

Varying the `text` part to see change. E.g. change to some nonsense string "abcdefg", this should find no match.

### CODE REVIEW

**Comment by ywkim312** [comment]
I used the word `tsunami` and it didn't return any result. I took the word from my local dfr3 database that I copied over from dev mongodb. I also copied space database from dev to my local as well. Tried the word 'hazus` and `earthquake` didn't get any result. Maybe I am setting something wrong?

**Comment by longshuicy** [comment]
> I used the word `tsunami` and it didn't return any result. I took the word from my local dfr3 database that I copied over from dev mongodb. I also copied space database from dev to my local as well. Tried the word 'hazus`and`earthquake` didn't get any result. Maybe I am setting something wrong?

@navarroc could you also try see if you have the same issue?

**Comment by navarroc** [comment]
Can we deploy this branch on dev for testing?

**Comment by navarroc** [comment]
Can you provide an example search that should fail on incore.ncsa but pass on incore-tst?

**Comment by longshuicy** [comment]
> Can you provide an example search that should fail on incore.ncsa but pass on incore-tst?

When you search no matter what keyword in incore prod it just return everything. Now on incore-tst it actually narrow things down.

Try `Epanet` maybe? This should only return 1 result

**Review by navarroc — APPROVED** [review]

**Pull request merged**
