### PR TITLE
167 update semantics service to use jersey 3 and open api 3

### PR DESCRIPTION
**Pull request by longshuicy**
Test these two endpoints:

GET http://localhost:8080/semantics/api/types
GET http://localhost:8080/semantics/api/types/incore:roadwayFragilityMapping

with admin presented in x-auth-usergroup
e.g. {"groups": ["incore_user", "incore_coe", "incore_admin"]}

### CODE REVIEW

**Comment by ylyangtw** [comment]
it's working but it returns nothing. I copied semanticsdb from dev mongodb but still getting empty results. Should I also copy other db?

**Comment by longshuicy** [comment]
> it's working but it returns nothing. I copied semanticsdb from dev mongodb but still getting empty results. Should I also copy other db?
You might want to update the "space" collection in the spacedb from incore-dev. I ingested all those semantics document id to corresponding spaces yesterday.

**Review by ylyangtw — APPROVED** [review]
endpoints work after updating the space collection. approve!

**Review by Rashmil-1999 — APPROVED** [review]
Just need to update the Changelog

**Pull request merged**
