### PR TITLE
182 improve the semantics template

### PR DESCRIPTION
**Pull request by longshuicy**
image

Try http://localhost:8080/semantics/api/types/ergo:hazusAggregatedPipelineDamage with postman. select "preview" in the response section

### CODE REVIEW

**Comment by longshuicy** [comment]
you have to make sure to not use "application/json" in you request

**Comment by navarroc** [comment]
> I am not setting any content-type at all in my request. Should I set it up to something specific? There are many options but I don't know what to select

Default content type I think will be application/json if you don't set an "Accept" header. You need to add Accept: text/html to get the HTML returned.

**Review by navarroc — APPROVED** [review]

**Comment by ylyangtw** [comment]
image
Looks nice! Approve~

**Review by ylyangtw — APPROVED** [review]

**Review by ywkim312 — APPROVED** [review]

**Review by Rashmil-1999 — APPROVED** [review]

**Comment by Rashmil-1999** [comment]
Screenshot 2023-07-19 at 12 43 55 PM

This is what I get... what am I setting wrong? I know my branch is right and that there are no errors on the server log

**Comment by longshuicy** [comment]
> Screenshot 2023-07-19 at 12 43 55 PM
> This is what I get... what am I setting wrong? I know my branch is right and that there are no errors on the server log

This is only implemented for /types/{name} endpoint. Not for the overall list

**Pull request merged**
