### PR TITLE
163 update hazard service to use jersey 3 and open api 3

### PR DESCRIPTION
**Pull request by ylyangtw**
Changed these annotations following the docs: [Migrating from SpringFox](https://springdoc.org/migrating-from-springfox.html) and [Describing Request Body](https://swagger.io/docs/specification/describing-request-body/)
Here are the annotations different from PR #152:
```
@Api → @Tag
@ApiResponse(code = 404, message = "foo") → @ApiResponse(responseCode = "404", description = "foo")
@ApiImplicitParam → @RequestBody
@ApiModel → @Schema
```
For testing, please test the following after running hazard service:
1. Check the swagger doc
http://localhost:8080/hazard/api/openapi.json
2. Test endpoints
[GET] http://localhost:8080/hazard/api/floods/
[GET] http://localhost:8080/hazard/api/tsunamis/5bc9eaf7f7b08533c7e610e1
[GET] http://localhost:8080/hazard/api/hurricanes/search?text=a
[POST] http://localhost:8080/hazard/api/earthquakes
[DELETE] http://localhost:8080/hazard/api/earthquakes/5c62e727c11bb30659444248

Scripts for testing using curl: (copy paste friendly if you are using your local mongodb)
```
curl -i -X GET \
   -H "x-auth-userinfo:{\"preferred_username\":\"commresilience\"}" \
   -H "x-auth-usergroup:{\"groups\":[\"incore_admin\"]}" \
 'http://localhost:8080/hazard/api/floods'

curl -i -X GET \
   -H "x-auth-userinfo:{\"preferred_username\":\"commresilience\"}" \
   -H "x-auth-usergroup:{\"groups\":[\"incore_admin\"]}" \
 'http://localhost:8080/hazard/api/tsunamis/5bc9eaf7f7b08533c7e610e1'

curl -i -X GET \
   -H "x-auth-userinfo:{\"preferred_username\":\"commresilience\"}" \
   -H "x-auth-usergroup:{\"groups\":[\"incore_admin\"]}" \
 'http://localhost:8080/hazard/api/hurricanes/search?text=a'

curl --location 'http://localhost:8080/hazard/api/earthquakes' \
--header 'x-auth-userinfo: {"preferred_username":"commresilience"}' \
--header 'x-auth-usergroup: {"groups": ["incore_admin"]}' \
--form 'earthquake="{
   \"name\":\"yytest\",
   \"description\":\"yytest\",
   \"eqType\":\"model\",
   \"attenuations\":{
      \"ChiouYoungs2014\":\"1.0\"
   },
   \"eqParameters\":{
      \"srcLatitude\":40.177,
      \"srcLongitude\":-111.426,
      \"magnitude\":\"5.5\",
      \"depth\":\"11.2\",
      \"region\":\"\",
      \"faultTypeMap\":{
         \"ChiouYoungs2014\":\"Normal\"
      }
   },
   \"visualizationParameters\":{
      \"demandType\":\"PGA\",
      \"demandUnits\":\"g\",
      \"minX\":-112.312,
      \"minY\":40.277,
      \"maxX\":-111.462,
      \"maxY\":41,
     
      \"numPoints\":\"1025\",
      \"amplifyHazard\":\"true\"
   }
}"'

curl --location --request DELETE 'http://localhost:8080/hazard/api/earthquakes/5c62e727c11bb30659444248' \
--header 'x-auth-userinfo: {"preferred_username":"commresilience"}' \
--header 'x-auth-usergroup: {"groups": ["incore_admin"]}'
```

### CODE REVIEW

**Review by longshuicy — APPROVED** [review]
Thank you for the write-ups! They are all very helpful ~~
I tested the listed endpoints they all seems to work. Approving.

**Comment by longshuicy** [comment]
I did get a few warning in the console though. Wonder if anyone else see those and are they serious?
```
FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

````

**Review by longshuicy — COMMENTED** [review]
sorry one last thing
You can remove 
`implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.5'`
and
`implementation group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.4.9'`
since they are not being used

**Comment by ylyangtw** [comment]
> I did get a few warning in the console though. Wonder if anyone else see those and are they serious?
> 
> ```
> FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
> 	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
> 	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
> 	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
> 	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
> 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
> 	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
> 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
> 	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
> 	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
> 	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
> 	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
> 	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
> 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
> 	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
> 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
> 	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
> 	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
> 	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
> 	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
> 	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
> 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
> 	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
> 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
> 	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> FileVisit failed: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> java.nio.file.NoSuchFileException: /Users/cwang138/Documents/INCORE-2.0/incore/server/data-service/build/classes/java/main
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
> 	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
> 	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
> 	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
> 	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
> 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
> 	at org.eclipse.jetty.util.Scanner.scanFiles(Scanner.java:724)
> 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:708)
> 	at org.eclipse.jetty.util.Scanner$ScanTask.run(Scanner.java:145)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> ```

Yeah I noticed this too. I think it's because that `POST /hazard/api/earthquakes` calls data service but we only run hazard service locally, so data service is unavailable.

**Comment by ylyangtw** [comment]
> sorry one last thing You can remove `implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.5'` and `implementation group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.4.9'` since they are not being used

Thanks for checking!

**Review by Vismayak — APPROVED** [review]

**Pull request merged**
