### PR TITLE
272 apply inner join when merging with parent

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Comment by longshuicy** [comment]
For testing a specific scenario for community app:
- could we try post this CSV file with partial retrofit buildings in SLC 
[SLC_retrofit_plan.csv](https://github.com/IN-CORE/incore-services/files/14350093/SLC_retrofit_plan.csv)
- merge it with `sourceDataset: 62fea288f5438e1f8c515ef8` 
- check the generated layer see if it's a intersection of both
- benchmark SLC performance

**Comment by ywkim312** [comment]
> For testing a specific scenario for community app:
> 
> * could we try post this CSV file with partial retrofit buildings in SLC
>   [SLC_retrofit_plan.csv](https://github.com/IN-CORE/incore-services/files/14350093/SLC_retrofit_plan.csv)
> * merge it with `sourceDataset: 62fea288f5438e1f8c515ef8`
> * check the generated layer see if it's a intersection of both
> * benchmark SLC performance

Is this deployed to dev? It might be easier if it gets deployed

**Comment by ylyangtw** [comment]
Just realized I am not sure how to test this PR ^^|||

**Comment by longshuicy** [comment]
Here is how you can test

### Step 1: POST to https://incore-dev.ncsa.illinois.edu/data/api/datasets/ with form data
```
{
    "title": "Galveston retrofit strategy plan",
    "description": "table that records guid and strategy method",
    "contributors": [],
    "dataType": "incore:retrofitStrategy",
    "storedUrl": "63ff69a96d3b2a308baaca12",
    "format": "table",
    "sourceDataset": "62fea288f5438e1f8c515ef8"
}
```
Headers (10)

### Step 2: POST to [https://incore-dev.ncsa.illinois.edu/data/api/datasets/{id}files](https://incore-dev.ncsa.illinois.edu/data/api/datasets/%7Bid%7Dfiles)
with file. 
Authorization

### Step 3: Check Geoserver layer preview https://incore-dev.ncsa.illinois.edu/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?3&filter=false search for that dataset ID

**Review by ylyangtw — APPROVED** [review]

**Review by longshuicy — APPROVED** [review]

**Pull request merged**
