### PR TITLE
Add endpoints to control steps in maestro service #34

### PR DESCRIPTION
**Pull request by longshuicy**
Add a few GET endpoints. **But this overall design might need to go away and start from scratch**

To test:
Import this document to mongodb --> maestrodb --> Playbook collection
```
{ 
    "_id" : ObjectId("615f1fe1cc6ea674bac38455"), 
    "className" : "edu.illinois.ncsa.incore.service.maestro.models.Playbook", 
    "name" : "Joplin Community Resilience Playbook", 
    "description" : "Includes Tornado building damage", 
    "tags" : [
        "playbook", 
        "resiliency"
    ], 
    "steps" : [
        {
            "className" : "edu.illinois.ncsa.incore.service.maestro.models.Step", 
            "id" : "1", 
            "description" : "Form Collaborative Planning Team", 
            "status" : "complete", 
            "substeps" : [
                {
                    "className" : "edu.illinois.ncsa.incore.service.maestro.models.TeamSubStep", 
                    "users" : [
                        "user1"
                    ], 
                    "id" : "1-1", 
                    "name" : "Identify Leader", 
                    "description" : "Identify resilience leader for the community", 
                    "status" : "pending", 
                    "required" : true
                }, 
                {
                    "className" : "edu.illinois.ncsa.incore.service.maestro.models.TeamSubStep", 
                    "users" : [
                        "user2", 
                        "user3"
                    ], 
                    "id" : "1-2", 
                    "name" : "Identify team members", 
                    "description" : "Identify team members and their roles and responsibilities", 
                    "status" : "pending", 
                    "required" : true, 
                    "requiredSteps" : [
                        "1-1"
                    ]
                }
            ]
        }, 
        {
            "className" : "edu.illinois.ncsa.incore.service.maestro.models.Step", 
            "id" : "2", 
            "description" : "Understanding the Situation", 
            "status" : "pending", 
            "substeps" : [
                {
                    "className" : "edu.illinois.ncsa.incore.service.maestro.models.SituationSubStep", 
                    "inputs" : [
                        {
                            "className" : "edu.illinois.ncsa.incore.service.maestro.models.Input", 
                            "datasetId" : "building-id", 
                            "dataType" : "incore:dataset"
                        }, 
                        {
                            "className" : "edu.illinois.ncsa.incore.service.maestro.models.Input", 
                            "datasetId" : "epf-id", 
                            "dataType" : "incore:epf"
                        }
                    ], 
                    "id" : "2-4", 
                    "name" : "Characterize built environment", 
                    "description" : "", 
                    "status" : "inprogress", 
                    "required" : true
                }
            ]
        }, 
        {
            "className" : "edu.illinois.ncsa.incore.service.maestro.models.Step", 
            "id" : "3", 
            "description" : "Determine Goals & Objectives", 
            "status" : "pending", 
            "substeps" : [
                {
                    "className" : "edu.illinois.ncsa.incore.service.maestro.models.ObjectiveSubStep", 
                    "hazards" : [
                        {
                            "className" : "edu.illinois.ncsa.incore.service.maestro.models.Hazard", 
                            "hazardId" : "hazard-id", 
                            "hazardType" : "tornado"
                        }
                    ], 
                    "id" : "3-3", 
                    "name" : "Define community hazards", 
                    "description" : "", 
                    "status" : "inprogress", 
                    "required" : true
                }, 
                {
                    "className" : "edu.illinois.ncsa.incore.service.maestro.models.ObjectiveSubStep", 
                    "workflows" : [
                        {
                            "className" : "edu.illinois.ncsa.incore.service.maestro.models.Workflow", 
                            "workflowId" : "workflowId", 
                            "workflowDescription" : "workflowDescription"
                        }
                    ], 
                    "id" : "3-4", 
                    "name" : "Determine anticipated performance", 
                    "description" : "", 
                    "status" : "pending", 
                    "required" : true, 
                    "requiredSteps" : [
                        "2-4", 
                        "3-3"
                    ]
                }
            ]
        }
    ]
}
```

image

Then:
- GET http://localhost:8080/maestro/api/playbooks/615f1fe1cc6ea674bac38455/steps/1/substeps/1-2/requiredSteps
- GET http://localhost:8080/maestro/api/playbooks/615f1fe1cc6ea674bac38455/steps/1/substeps/1-2/status
- GET http://localhost:8080/maestro/api/playbooks/615f1fe1cc6ea674bac38455/steps/1/status

### CODE REVIEW

**Comment by navarroc** [comment]
There's a unit test for the maestro service that doesn't implement the new DAO methods.

**Comment by navarroc** [comment]
Any idea why we are checking if a user is an admin in the constructor of the PlaybookController?

**Comment by longshuicy** [comment]
> Any idea why we are checking if a user is an admin in the constructor of the PlaybookController?

Because we are not exposing those endpoints to users yet.

**Comment by navarroc** [comment]
> > Any idea why we are checking if a user is an admin in the constructor of the PlaybookController?
> 
> Because we are not exposing those endpoints to users yet.

I should really read the comments. Doh!

**Comment by longshuicy** [comment]
> There's a unit test for the maestro service that doesn't implement the new DAO methods.

will fix that and let you know

**Review by navarroc — APPROVED** [review]

**Comment by longshuicy** [comment]
We are starting a new repo and using python fastAPI for maestro services. I don't think we'll need this PR anymore?

**Pull request closed without merging**
